name: schedule

on:
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      
      - name: FPL Code
        run : 
          Rscript -e 'source("FPL_API.R")'
        env : 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Standings.csv
          git add Gameweek.csv
          git add Historic_Seasons.csv
          git add Player.csv
          git add Fixtures.csv
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
