name: Manual Run

on:
  workflow_dispatch:
  
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R  #Specify which versino of R to set up
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.3'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcurl4-openssl-dev libxml2-dev

      - name: Set up renv
      - uses: r-lib/actions/setup-renv@v2
      
      - name: FPL Code
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          GOOGLE_SHEETS_URL: ${{ vars.GOOGLE_SHEETS_URL }}
        run : Rscript -e 'source("FPL_API.R")'
      
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Standings.csv
          git add Gameweek.csv
          git add Historic_Seasons.csv
          git add Player.csv
          git add Fixtures.csv
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
