name: Test

on:
   #workflow_run:
   workflow_dispatch:
    #workflows: ["5:30 Schedule", "Manual Run"]
    #types:
      #- completed

jobs:
  dashboard_refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Install Dependencies
        run: |
           sudo apt-get update
           sudo apt-get install -y wget gnupg ca-certificates
           wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
           sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
           sudo apt-get update
           sudo apt-get install -y google-chrome-stable
           sudo snap install chromium
           pip install selenium
           pip install webdriver-manager

      - name: Run Script
        env: 
          TABLEAU_EMAIL: ${{ vars.TABLEAU_EMAIL }}
          TABLEAU_PASSWORD: ${{ vars.TABLEAU_PASSWORD }}
        run: python Test.py
